version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /tools/mock-fv-ssh-server
    schedule:
      interval: weekly
      day: monday
      time: "10:05"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:20"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5
